### PR TITLE
fix: return "0x00" for normalize(0)

### PR DESCRIPTION
**Pull request by legobeat**
The `normalize` function returns `0x${number}` for all numbers except `0`, for which it returns `undefined`. This changes it to return `0x00` for `0`.

### CODE REVIEW

**Review by kumavis — DISMISSED** [review]
good

this is a breaking change

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by mikesposito** [comment]
I didn't notice this PR before opening this one: https://github.com/MetaMask/eth-sig-util/pull/315
@legobeat I am thinking if maybe #315 could solve the problem you are trying to fix?

**Comment by mcmire** [comment]
@mikesposito @legobeat This seems complementary to #315. I don't see a reason why we couldn't have both. Do you?

**Review by mcmire — APPROVED** [review]
Makes sense.

**Comment by mikesposito** [comment]
@mcmire We can definitely have both, I was just pointing out that after #315 has been merged, the early function termination does not affect `0` input anymore, so from this PR we could also just add the test

**Comment by Gudahtt** [comment]
I don't think the functional change made in this PR is relevant anymore. The change in #315 is functionally equivalent in the case where zero is passed in, though broader in that it also affects the case where an empty string is passed in.

Agreed that the test would be useful to include though!

**Comment by Gudahtt** [comment]
I have created a separate PR to add just the test: https://github.com/MetaMask/eth-sig-util/pull/317

**Comment by Gudahtt** [comment]
Superseded by #315 and #317

**Pull request closed without merging**
