### PR TITLE
Migrate from CircleCI to GitHub Actions

### PR DESCRIPTION
**Pull request by Gudahtt**
All CI checks have been migrated to GitHub actions, using our MetaMask module template example workflow. The main difference between this and the template workflow is the addition of the `test:browser` command for running browser tests.

This should work similarly to the CircleCI workflow. The main differences are that now unit tests, the linter, and browser tests are run with all three supported Node.js versions (previously they were run with Node.js v12, except unit tests which were also run with v14). Also we now have dependency caching, so hopefully the workflows will be faster. The HAR archive from installation has been omitted as well.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon #147

**Comment by Gudahtt** [comment]
Note that the build failure is just from CircleCI, which has had its config removed in this branch. I can disable CircleCI status updates and update the required status updates in our branch protection rules once this has been approved.

**Review by rekmarks — APPROVED** [review]
We could (probably should?) separate building from testing at the script level and note that the GitHub workflow builds as well as lints and tests, but I won't block on it!

**Comment by Gudahtt** [comment]
Oh, good idea! I'll do that in a follow up PR.

**Comment by Gudahtt** [comment]
Actually, on second thought, it would be challenging to split them apart. If we do that, we risk `yarn test` blowing up with a confusing error message when the build doesn't exist. Or even worse, it could run using an outdated build. We could prevent that by checking to see if there was a build first, but I'm not sure it's worth the effort.

I'll soon be converting these tests to Jest, then migrating them to TypeScript. At that point, the special test bundle and the build step will no longer be required for testing, so they will be removed. Maybe we can just wait until then to clean all of this up.

**Pull request merged**
