### PR TITLE
v3.0.1

### PR DESCRIPTION
**Pull request by Gudahtt**
This release includes dependency updates and removals.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon #128

**Review by rekmarks — APPROVED** [review]

**Comment by Gudahtt** [comment]
>A new version of the package eth-sig-util (3.0.1) was published at 2021-02-05T02:52:38.317Z from
[redacted]. The shasum of this package was 8753297c83a3f58346bd13547b59c4b2cd110c96.

**Review by 01SMD — COMMENTED** [review]
.

**Review by 01SMD — COMMENTED** [review]
.

**Pull request merged**
