### PR TITLE
Add TypeScript declaration file

### PR DESCRIPTION
**Pull request by edhedges**
Changes include:
- Adding the [TypeScript declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) `index.d.ts` containing the modules definition.
- Add "types" property to `package.json` per the [docs]( https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package)
- Bump minor version
- Change to package-lock.json that occurred after installing dependencies to run tests and `npm pack`.

### CODE REVIEW

**Comment by edhedges** [comment]
I would appreciate some input / feedback on the type definitions I've proposed. I am particularly interested in knowing if you have suggestions for the `TMsgParams` type.

**Comment by danfinlay** [comment]
For the types and especially of that method, I’d like to hear from @bitpshr

I’d rather no package lock changes to this module in a PR, I’ll run an npm install before the next deploy.

**Comment by edhedges** [comment]
@danfinlay I reverted the changes to `package-lock.json` and will await feedback from @bitpshr 

thanks

**Comment by edhedges** [comment]
@bitpshr any updates for me?

**Comment by lazaridiscom** [comment]
@danfinlay , file was added within 3a3a3dd0201d9c78a5c6e9256fec8a4a7ba76829, so this one here should be closable.

**Comment by lazaridiscom** [comment]
> lazaridiscom unassigned bitpshr 23 seconds ago

strange, i did nothing, besides posting the above https://github.com/MetaMask/eth-sig-util/pull/43#issuecomment-558907872

**Comment by danfinlay** [comment]
Hey @edhedges, sorry, I merged another definition file since this. I hope it works for you, and if it doesn't, maybe we can reopen this and merge yours with it or instead of it.

**Pull request closed without merging**
