### PR TITLE
Add `TypedDataUtils.findTypeDependencies` tests

### PR DESCRIPTION
**Pull request by Gudahtt**
This function is now comprehensively tested.

### CODE REVIEW

**Comment by Gudahtt** [comment]
This depends upon #167

**Review by rekmarks — APPROVED** [review]
LGTM!

Let me also suggest that we do this: #179

**Comment by Gudahtt** [comment]
This has been rebased to resolve conflicts

**Review by rekmarks — APPROVED** [review]
LGTM!

**Pull request merged**
