### PR TITLE
ci - test against multiple node versions

### PR DESCRIPTION
**Pull request by kumavis**
https://github.com/MetaMask/eth-sig-util/issues/85 suggests we're signing different on different node versions.

This PR runs CI against different node versions and chrome

this PR does not reproduce the issue in #85 
a test for that should be added when the details are known

### CODE REVIEW

**Comment by kumavis** [comment]
need to test in browser or at least a browserify bundle

**Comment by kumavis** [comment]
added browser tests via `browserify` and `smokestack`
took too long grumble grumble

**Comment by kumavis** [comment]
do we need to fan in to a all-tests-pass for an easier github required test check?

**Comment by whymarrh** [comment]
> do we need to fan in to a all-tests-pass for an easier github required test check?

Yes please, I was hoping to add that to the workflow at some point but it fell off my radar before we started using this same workflow in a few places

**Comment by kumavis** [comment]
@whymarrh did the fan in and set `all-tests-pass` as a github expected CI check

**Pull request merged**
