### PR TITLE
Add dependabot to keep modern dependencies

### PR DESCRIPTION
**Pull request by darkwing**

### CODE REVIEW

**Review by RonSherfey — APPROVED** [review]

**Review by RonSherfey — APPROVED** [review]

**Review by RonSherfey — APPROVED** [review]

**Review by Gudahtt — CHANGES_REQUESTED** [review]
This should be updated to match our new Dependabot config template, which only updates `@metamask` dependencies.

**Review by RonSherfey — APPROVED** [review]
approved changes

**Review by RonSherfey — APPROVED** [review]

**Comment by danfinlay** [comment]
I've blocked that bot.

**Comment by Gudahtt** [comment]
This has been superseded by #145

**Pull request closed without merging**
